version: '3.8'

services:
  etl-dev:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - .:/app
      - ./data:/app/data
    env_file: .env
    ports:
      - "8888:8888"
    command: tail -f /dev/null

  etl-prod:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    volumes:
      - .:/app
      - ./data:/app/data
    env_file: .env
    command: python src/main.py
